FROM perl:5.26
ARG TAG=0.001
USER root
################## MAINTAINER ######################
MAINTAINER Yumi Sims yy5@sanger.ac.uk
################## INSTALLATION ######################

COPY --chmod=0755 scripts/fa2cmap_multi_color.pl /usr/local/bin/
COPY --chmod=0755 scripts/rename_cmapids.pl /usr/local/bin/

